require 'rubygems'
require 'rake'
require 'rake/clean'
require 'rdoc/task'
require 'rake/testtask'

task :default => :test

Rake::RDocTask.new do |rdoc|
  files =['lib/**/*.rb']
  rdoc.rdoc_files.add(files)
  rdoc.title = "An Introduction to Sinatra Docs"
  rdoc.rdoc_dir = 'doc/rdoc' # rdoc output folder
  rdoc.options << '--line-numbers'
end

Rake::TestTask.new do |t|
  t.libs << 'lib'
  t.libs << "test"
  t.pattern = 'test/**/*_test.rb'
  t.verbose = false
end

task :console do
  require 'irb'
  require 'irb/completion'
  require './lib/my_app'
  ARGV.clear
  IRB.start
end
